apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shubhamprataps/ArgocD.git
    targetRevision: HEAD
    path: deployment/app1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: demo1-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false